# Stage 1: Build the application
FROM node:22-alpine AS builder

# Create app directory
WORKDIR /app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY backend/package*.json ./
RUN npm install

# Bundle app source
COPY backend/ ./

# Stage 2: Create the production image
FROM node:22-alpine

WORKDIR /app

# Copy dependencies from the builder stage
COPY --from=builder /app/node_modules ./node_modules

# Copy the application code from the builder stage
COPY --from=builder /app/ ./

# Expose the port the app runs on
EXPOSE 3001

# Command to run the application
CMD ["npm", "start"]
